# Intent definition for Calendar skill
#
#  (c) A. Dominik, 2020
#
skill = "ADoSnipsShoppinglistDE"
developer = "andreasdominik"


[inventory]
intents = ["shoppinglistPrint", "shoppinglistDeleteItem",
           "shoppinglistAddItem", "shoppinglistRead",
           "shoppinglistDeleteList", "shoppinglistCheck"]
slots = ["Item", "Item2", "Item3", "Unit", "Unit2", "Unit3", "Quantity", "Quantity2", "Quantity3"]


# define slots:
# Types: "Any", "ListOfValues", "Time", "Duration", "Currency", "Number", "Ordinal"
#
[Item]
slot_type = "Any"
allow_empty = false

[Item2]
slot_type = "Any"
allow_empty = false

[Item3]
slot_type = "Any"
allow_empty = false

[Unit]
slot_type = "ListOfValues"
allow_empty = false

        [Unit.synonyms]
        "Tube" = ["Tuben", "Tube"]
        "klein" = ["kleiner", "kleine", "kleinen", "klein",
                   "kurzer", "kurzen", "kurze", "kurz"]
        "groß" = ["großer", "großen", "große", "groß"]
        "Becher" = "Becher"
        "Tüte" = ["Tüten", "Tüte"]
        "Tafel" = ["Tafeln", "Tafel"]
        "Dose" = ["Dosen", "Dose", "Büchsen", "Büchse"]
        "Glas" = ["Glas", "Gläser"]
        "Schachtel" = ["Schachteln", "Schachtel", "Boxen", "Box"]
        "Packung" = ["Packungen", "Packung", "Pack", "Päckchen"]
        "Stück" = ["Stücke", "Stück"]
        "Flasche" = ["Flaschen", "Flasche"]
        "Gramm" = ["Gramm", "g"]
        "Kilogramm" = ["Kilogramm", "kg", "Kilos", "Kilo"]
        "Kasten" = ["Kasten", "Kästen", "Tragerl", "Kisten", "Kiste", "Ständer"]
        "Liter" = ["Liter", "l "]

[Unit2]
slot_type = "ListOfValues"
allow_empty = false

        [Unit2.synonyms]
        "Tube" = ["Tuben", "Tube"]
        "klein" = ["kleiner", "kleine", "kleinen", "klein",
                   "kurzer", "kurzen", "kurze", "kurz"]
        "groß" = ["großer", "großen", "große", "groß"]
        "Becher" = "Becher"
        "Tüte" = ["Tüten", "Tüte"]
        "Tafel" = ["Tafeln", "Tafel"]
        "Dose" = ["Dosen", "Dose", "Büchsen", "Büchse"]
        "Glas" = ["Glas", "Gläser"]
        "Schachtel" = ["Schachteln", "Schachtel", "Boxen", "Box"]
        "Packung" = ["Packungen", "Packung", "Pack", "Päckchen"]
        "Stück" = ["Stücke", "Stück"]
        "Flasche" = ["Flaschen", "Flasche"]
        "Gramm" = ["Gramm", "g"]
        "Kilogramm" = ["Kilogramm", "kg", "Kilos", "Kilo"]
        "Kasten" = ["Kasten", "Kästen", "Tragerl", "Kisten", "Kiste", "Ständer"]
        "Liter" = ["Liter", "l "]

[Unit3]
slot_type = "ListOfValues"
allow_empty = false

        [Unit3.synonyms]
        "Tube" = ["Tuben", "Tube"]
        "klein" = ["kleiner", "kleine", "kleinen", "klein",
                   "kurzer", "kurzen", "kurze", "kurz"]
        "groß" = ["großer", "großen", "große", "groß"]
        "Becher" = "Becher"
        "Tüte" = ["Tüten", "Tüte"]
        "Tafel" = ["Tafeln", "Tafel"]
        "Dose" = ["Dosen", "Dose", "Büchsen", "Büchse"]
        "Glas" = ["Glas", "Gläser"]
        "Schachtel" = ["Schachteln", "Schachtel", "Boxen", "Box"]
        "Packung" = ["Packungen", "Packung", "Pack", "Päckchen"]
        "Stück" = ["Stücke", "Stück"]
        "Flasche" = ["Flaschen", "Flasche"]
        "Gramm" = ["Gramm", "g"]
        "Kilogramm" = ["Kilogramm", "kg", "Kilos", "Kilo"]
        "Kasten" = ["Kasten", "Kästen", "Tragerl", "Kisten", "Kiste", "Ständer"]
        "Liter" = ["Liter", "l "]

[Quantity]
slot_type = "Number"
allow_empty = false

[Quantity2]
slot_type = "Number"
allow_empty = false

[Quantity3]
slot_type = "Number"
allow_empty = false


# define phrases for intent recognition:
# "exact", "regex", "partial", "ordered"
#
[shoppinglistPrint]
printShoppingList1 = "partial: <<Bitte|>> drucke <<mir|>> <<die|den>> <<Einkaufszettel|Einkaufsliste>>"
printShoppingList2 = "partial: <<Bitte|>> mach? einen Ausdruck <<der|vom>> <<Einkaufszettel|Einkaufsliste>>"

[shoppinglistDeleteItem]
deleteShoppingList1 = "partial: <<Bitte|>> <<>> <<Item>> <<vom|von der>> <<Einkaufszettel|Einkaufsliste>> <<streichen|entfernen|löschen>>"
deleteShoppingList2 = "partial: <<Bitte|>> <<streiche|entferne|lösche>> <<>> <<Item>> <<vom|von der>> <<Einkaufszettel|Einkaufsliste>>"
deleteShoppingList3 = "partial: <<Bitte|>> <<streiche|entferne|lösche>> <<>> <<Item>> <<vom|von der>> <<Einkaufszettel|Einkaufsliste>>"
deleteShoppingList4 = "partial: Du kannst <<>> <<Item>> <<vom|von der>> <<Einkaufszettel|Einkaufsliste>> <<streichen|entfernen|löschen>>"

[shoppinglistAddItem]
add_a_3 = "partial: <<Bitte|>> <<schreibe|setze>> <<bitte|>> <<Quantity>> <<Unit>> <<Item>> und <<Quantity2>> <<Unit2>> <Item2>> und <<Quantity3>> <<Unit3>> <<Item3>> <<auf den|auf die>> <<Einkaufszettel|Einkaufsliste>>"
add_b_2 = "partial: <<Bitte|>> <<schreibe|setze>> <<bitte|>> <<Quantity>> <<Unit>> <<Item>> und <<Quantity2>> <<Unit2>> <Item2>> <<auf den|auf die>> <<Einkaufszettel|Einkaufsliste>>"
add_c_1 = "partial: <<Bitte|>> <<schreibe|setze>> <<bitte|>> <<Quantity>> <<Unit>> <<Item>> <<auf den|auf die>> <<Einkaufszettel|Einkaufsliste>>"

add_d_3 = "partial: <<Bitte|>> <<schreibe|setze>> <<bitte|>> <<Item>> und <<Item2>> und <<Item3>> <<auf den|auf die>> <<Einkaufszettel|Einkaufsliste>>"
add_e_2 = "partial: <<Bitte|>> <<schreibe|setze>> <<bitte|>> <<Item>> und <<Item2>> <<auf den|auf die>> <<Einkaufszettel|Einkaufsliste>>"
add_f_1 = "partial: <<Bitte|>> <<schreibe|setze>> <<bitte|>> <<Item>> <<auf den|auf die>> <<Einkaufszettel|Einkaufsliste>>"

add_k_3_Alt = "partial: <<wir|ich>> brauche? <<noch|>> <<Item>> und <<item2>> und <<item3>>"
add_l_2_Alt = "partial: <<wir|ich>> brauche? <<noch|>> <<Item>> und <<item2>>"
add_m_1_Alt = "partial: <<wir|ich>> brauche? <<noch|>> <<Item>>"
add_n_AltUnit = "partial: <<wir|ich>> brauche? <<noch|>> <<Quantity>> <<Unit>> <<Item>>"

[shoppinglistRead]
readShoppingList1 = "ordered: lies mir <<Einkaufszettel|Einkaufsliste>> vor"
readShoppingList2 = "partial: was steht auf <<dem|der>> <<Einkaufszettel|Einkaufsliste>>"

[shoppinglistDeleteList]
delListAll = "exact: <<bitte|>> lösche <<bitte|>> <<den|die>> <<Einkaufszettel|Einkaufsliste>>"
delListAll2 = "exact: <<bitte|>> lösche <<bitte|>> alles <<vom|von der>> <<Einkaufszettel|Einkaufsliste>>"

[shoppinglistCheck]
listCheck = "partial: <<ist|steht>> <<Item>> <<schon|bereits|>> auf <<der|dem>> <<Einkaufszettel|Einkaufsliste>>"
liste2Check = "partial: <<ist|steht>> auf <<der|dem>> <<Einkaufszettel|Einkaufsliste>> <<schon|bereits|>> <<Item>>"
