Snips.addText("de", :dunno,  "Ich habe nicht verstanden was ich machen soll!")
Snips.addText("de", :new_list, "Ich lege einen neue Einkaufszettel an.")
Snips.addText("de", :i_add, "Ich schreibe auf den Einkaufszettel ")
Snips.addText("de", :already_there, "steht bereits auf dem Einkaufszettel.")
Snips.addText("de", :not_there, "steht noch nicht auf dem Einkaufszettel.")
Snips.addText("de", :del_item, "wird vom Einkaufszettel gelöscht!")
Snips.addText("de", :the_list_reads, "Auf dem Einkaufszettel steht:")
Snips.addText("de", :no_list, "Die Einkaufsliste ist leer.")
Snips.addText("de", :ask_delete, "Soll der Einkaufszettel wirklich gelöscht werden?")
Snips.addText("de", :delete_list, "Der Einkausfzettel wird gelöscht!")
Snips.addText("de", :abort_delete, "OK, der Einkaufszettel wir nicht gelöscht!")
Snips.addText("de", :no_printer, "In der Config-Datei ist kein Drucker konfiguriert!")
Snips.addText("de", :error_print, "Der Einkausfzettel kann leider nicht gedruckt werden")
Snips.addText("de", :i_print, "Ich drucke den Einkausfszettel aus")


Snips.addText("en", :dunno, "I did not catch what you want me to do!")
Snips.addText("en", :new_list, "I create a new shopping list.")
Snips.addText("en", :i_add, "I add to the shopping list: ")
Snips.addText("en", :already_there, "is already on the list.")
Snips.addText("en", :not_there, "is not on the list.")
Snips.addText("en", :del_item, "will be deleted.")
Snips.addText("en", :the_list_reads, "The shopping list is")
Snips.addText("en", :no_list, "the shopping list is empty!")
Snips.addText("en", :ask_delete, "Do you really want to delete the shopping list?")
Snips.addText("en", :delete_list, "The shopping list will be deleted completely!")
Snips.addText("en", :abort_delete, "OK, I will not delete the shopping list")
Snips.addText("en", :no_printer, "There is no printer configured in the config-file!")
Snips.addText("de", :error_print, "Error printing the shopping list")
Snips.addText("de", :i_print, "I am printing the shopping list")
